# Generated by Django 3.1.2 on 2020-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Founder', models.CharField(max_length=25)),
                ('Location', models.TextField()),
                ('Branches', models.PositiveIntegerField()),
                ('Total_staff', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('Subjects', models.CharField(max_length=25)),
                ('Skills', models.TextField()),
                ('Experience_in_years', models.PositiveIntegerField()),
                ('Present_salary', models.PositiveIntegerField()),
            ],
        ),
    ]
